#ifdef CONFIG_TOP
#include "../proffieboard_v3_config.h"
#define NUM_BLADES 3
#define NUM_BUTTONS 1


const unsigned int maxLedsPerStrip = 500;
#define EXTRA_COLOR_BUFFER_SPACE 60

#define CLASH_THRESHOLD_G 3.0

#define ENABLE_MOTION
#define ENABLE_WS2811
#define ENABLE_SD
#define ENABLE_SERIAL

//Audio
#define VOLUME 1000
#define BOOT_VOLUME 450
#define ENABLE_AUDIO
#define KILL_OLD_PLAYERS
#define FILTER_CUTOFF_FREQUENCY 100
#define FILTER_ORDER 8
#define NO_REPEAT_RANDOM


#define MOTION_TIMEOUT 60 * 2 * 1000
#define IDLE_OFF_TIME 60 * 5 * 1000



//bladeid
#define SHARED_POWER_PINS
#define BLADE_ID_SCAN_MILLIS 2000
#define BLADE_ID_TIMES 5
#define ENABLE_POWER_FOR_ID PowerPINS<bladePowerPin2>



#define ENABLE_ALL_EDIT_OPTIONS
#define SAVE_PRESET
#define DISABLE_BASIC_PARSER_STYLES
#define ENABLE_DEVELOPER_COMMANDS
#define COLOR_CHANGE_DIRECT




#define FETT263_EDIT_MODE_MENU
#define FETT263_SPECIAL_ABILITIES
#define FETT263_DUAL_MODE_SOUND
#define FETT263_CLASH_STRENGTH_SOUND
#define FETT263_MAX_CLASH 8
#define FETT263_DISABLE_MULTI_BLAST_TOGGLE
#define FETT263_DISABLE_QUOTE_PLAYER
#define FETT263_TRACK_PLAYER_NO_PROMPTS
#define FETT263_BATTLE_MODE_START_ON
#define FETT263_LOCKUP_DELAY 200
#define FETT263_BM_CLASH_DETECT 6
//#define FETT263_TWIST_OFF
#endif
